name: checks
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: shipfox-2vcpu-ubuntu-2404
    strategy:
      matrix:
        node-version: ["lts/iron", "latest"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn

      - run: yarn test

  lint:
    runs-on: shipfox-2vcpu-ubuntu-2404
    strategy:
      matrix:
        node-version: ["lts/iron", "latest"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn

      - run: yarn lint

  typecheck:
    runs-on: shipfox-2vcpu-ubuntu-2404
    strategy:
      matrix:
        node-version: ["lts/iron", "latest"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn

      - run: yarn typecheck
